@startuml

participant "Block Originator" as orig
collections "/blocks subscribers" as block_topic
participant "This Node" as this #lightblue


par
    orig -> block_topic: NewBlockHeader(header)
    block_topic -> this:
    this -> this: validate header
    alt invalid header
        this -> this: update invalid header (originator)
        note right
            a chance for a node
            to mark a peer as problematic
        end note
    end
else
    orig -> block_topic: NewBlockBody(body)
    block_topic -> this:
    this -> this: validate and\nupdate body
else
    orig -> block_topic: NewStateDiff(state_diff)
    block_topic -> this:
    this -> this: validate and\nupdate state
end

@enduml
