
@startuml

participant "This Node" as this #lightblue
participant "Peer" as peer

this -> peer: GetBlockHeaders(start_block,limit,direction)
note right
  start_block: starting block number
  limit: how many, at most, headers to retrieve
  direction: retrieve direction - forward/backward
end note
peer -> this: BlockHeaders(...)

par get bodies
    this -> peer: GetBlockBodies(start_block,limit,direction)
    peer -> this: BlockBodies(...)
else get state
    this -> peer: GetStateDiffs(start_block,limit,direction)
    peer -> this: StateDiffs(...)
end
@enduml
