
participant "This Node" as this #lightblue
participant "Peer" as peer

group sync headers
    note over this, peer
        as described under "Chain Synchronization"
    end note

    this -> peer:
    peer --> this:
end

loop while full state not received
    this -> peer: GetSnapshotStateChunk(chunk_number)
    peer -> this: StateSnapshotChunk(block_num,chunk_number, state_values, proof)
    this -> this: verify proof and apply chunk

    this -> peer: GetClassSnapshotChunk(chunk_number)
    note right: can also get class declarations

    peer -> this: ClassSnapshotChunk(block_num, chunk_number, classes, proof)

    this -> this: apply class declarations

    loop for remaining blocks from `block_number` to tip
        this -> peer: GetStateDiffs(start_block,limit,direction)
        peer -> this: StateDiffs(...)
        this -> this: apply state diffs
    end
    note right
         Apply state diffs up to tip for each chunk
    end note
end
