@startuml

participant "This Node" as this #lightblue
participant "Peer" as peer

note over this,peer: all nodes support transaction propagation


this -> peer: h1: KnownPooledTransactions(hashes)
this <- peer: h2: KnownPooledTransactions(hashes)

this -> peer: GetPooledTransactions(h2 \ h1)
note right of peer: Same flow the other way.\nNot shown for clarity
this <-- peer: PooledTransactions

this -> this: validate and add transactions to pool


@enduml
